name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: [self-hosted, ryazan]
    name: Build Frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> frontend/.env
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> frontend/.env
          echo "PORT=${{ secrets.PORT }}" >> frontend/.env

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t my-frontend-app:latest .

      - name: Save Docker image to a tar file
        run: |
          docker save my-frontend-app:latest -o my-frontend-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-frontend-app-tar
          path: frontend/my-frontend-app.tar

  deploy:
    runs-on: [self-hosted, ryazan]
    name: Deploy to Server
    needs: frontend-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: my-frontend-app-tar
          path: frontend/my-frontend-app.tar

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy Docker image to server
        env:
          SERVER_USER: deploy
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          sshpass -p $SERVER_PASSWORD scp frontend/my-frontend-app.tar $SERVER_USER@$SERVER_HOST:~/my-frontend-app.tar

      - name: Load and run Docker image on server
        env:
          SERVER_USER: deploy
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.PORT }}
        run: |
          sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_HOST << 'EOF'
          docker load -i ~/my-frontend-app.tar
          docker stop my-frontend-app || true
          docker rm my-frontend-app || true
          docker run -d -p $PORT:$PORT --env PORT=$PORT --name my-frontend-app my-frontend-app:latest
          EOF
