name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: self-hosted
    name: Build Frontend
    steps:
      - name: Change file permissions
        run: echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S chown -R $USER:$USER /home/github/actions-runner/_work/lct-2024

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> frontend/.env
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> frontend/.env
          echo "PORT=${{ secrets.PORT }}" >> frontend/.env

      - name: Build Docker image
        run: |
          cd frontend
          docker build --quiet -t lct-frontend:latest . > build_output.log 2>&1

      - name: Save Docker image to a tar file
        run: |
          docker save lct-frontend:latest -o lct-frontend.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: lct-frontend-tar
          path: frontend/lct-frontend.tar

      - name: Upload build log
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: frontend/build_output.log
